### ISSUE TITLE
Codelist Queries

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/risk-factors-research#68]
As discussed with @alexwalkercebm @hmcd, we are keeping a list of things we might want to think about changing in the codelists for the risk factor analysis: 

1. Removing brain tumours from Other Neurological Conditions as malignancy not included in other organ groups like no lung cancer in chronic respiratory disease
2. Removing spleen code for ??? @hmcd what was this one....

**Comment by HelenCEBM** [comment]
Liver disease includes the following codes, perhaps need to be checked/removed:
- G85.. (Oesophagael varices) or (other varicose veins)
- Q48yz (Other prinatal condition NOS) or (congen hepatic fibrosis)
- C3500 Hereditary haemochromatosis [doesn't necessarily involve liver damage?]

**Comment by HenryDrysdale** [comment]
On codelists.opensafely.org I have removed:

- "Excision of lesion of spleen (78412)" from the "Asplenia" codelist 
- All brain tumour codes from the "Other Neurological Conditions" codelist.

**Comment by alexwalkerepi** [comment]
I excluded the 3 codes that @HelenCEBM mentioned, and added `Congenital absence of thymus` to permanent immunosuppression.

We discussed `Transplant immunosuppression` and determined that it was already in both lists, and decided that this was okay given previous conversations on the impact of double counting on modelling, and that it was clear that it mean both transplant and immunosuppression.

**Comment by hmcd** [comment]
Thanks! 

@alexwalkercebm , I do think transplant immunosuppression should only be in the one list (organ transplant) as it only represents one type of risk. All the patients in the solid organ transplant list will be on permanent immunosuppressing drugs, so this code doesn't reflect a different risk - just a different code for the same concept. 

The rationale for the transplant codes with specified organs being in two lists is that there are two potential mechanisms represented for risk of infection :(1) immunosuppression associated with organ transplant and (2) the organ-specific disease (e.g. chronic liver disease). But that doesn't apply to this code - there's not a separate immunosuppressing mechanism of risk being described.

**Comment by CarolineMorton** [comment]
I think we can close this now as we have dealt with all the issues raised but please correct me if i am wrong

**Comment by Lextuga007** [comment]
Is there a corresponding lookup for the ethnicity groupings in https://github.com/opensafely/risk-factors-research/blob/master/codelists/opensafely-ethnicity.csv? I'm assuming (but could be wrong) that 1 is White but are their definitions somewhere?

Guessing still but is 4 in the Grouping_6 Black? African - ethnic category 2001 census comes up as White, Black and Mixed in groupings when I look at data I have access to that joins different clinical systems together. I'm not sure we can say African is black. It may need to go into the category Other because it cannot be determined that precisely.

**Comment by rohinimathur** [comment]
@Lextuga007 
Hi, there isn't a labelled list, but we should add the category labels to the codelist you have linked to- thanks!
Group 4 in the 6 category ethnicity is 'Black' which encompasses African, Caribbean, and other black ethnicities.
The ethnicity isn't assigned by us, but is self-reported by individuals to their GP. Their ethnicity is captured using the Read code in column two, and then we aggregate the codes into the standard 16 and 5 categories as per the census - which includes people who self-identify as African under the larger category of 'Black'.

https://www.ons.gov.uk/methodology/classificationsandstandards/measuringequality/ethnicgroupnationalidentityandreligion

You can see that some of the 'North African/Arab' ethnic groups are included under other. these standard categories are to ensure comparability with other national datasets, but if you have a specific research question in which you want to dissagregate or re-group people into different categories, then you can certainly do so. Standard categories are a bit arbitrary and may not suit all research purposes.
