### ISSUE TITLE
The `test_stata` workflow fails

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/risk-factors-research#93]
The `test_model` workflow fails ([stacktrace](https://github.com/opensafely/risk-factors-research/runs/2838899374?check_suite_focus=true)). The issue seems to be somewhere around lines 256-257 with the call to `sqlcmd`:

https://github.com/opensafely/risk-factors-research/blob/9e71bd0e32fb95944036d23f87fc804ef257297e/run.py#L249-L258

**Comment by evansd** [comment]
This won't pass now without significant work. It used to talk to a dummy database server (long since decommissioned).
